### ISSUE TITLE
Container fails to start: Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.

### ISSUE THREAD

**Issue by yllekz** [coderaiser/cloudcmd#357]
- **Version** (`cloudcmd -v`): docker-latest (v15.9.9)
- **Node Version** `node -v`: The one that ships with the docker container
- **OS** (`uname -a` on Linux): Linux 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
- **Browser name/version**: Firefox 94.0.2
- **Used Command Line Parameters**: none, used yml config file
- **Changed Config**: n/a?

Container does not start, it just spits this out in the logs repeatedly:

``Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.``

This is my docker-compose file - deployed via Portainer stack:

```
---
version: "2.1"
services:
  cloudcmd:
    image: coderaiser/cloudcmd:latest
    ports:
      - 7000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    restart: unless-stopped
```

**Comment by coderaiser** [comment]
@timoknapp do you have any ideas?

**Comment by timoknapp** [comment]
Hi @yllekz, 

on what OS architecture are you running this docker image? Is it running on `arm` e.g. Raspberry PI or sth. different?
Also do you have more logs on this, its really hard to understand the real issue based on this single log statement.

Regards

**Comment by yllekz** [comment]
I'm running the 32-bit Raspberry Pi OS which reports as ``armhf`` when I run ``dpkg --print-architecture``

Unfortunately I'm not sure where else to look in terms of logs. The line ``Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.`` is all I get from the container when trying to load it. If there's any other place to check, let me know and I'll drill into it.

**Comment by coderaiser** [comment]
@timoknapp could you please help, docker containers not created because of en error https://github.com/coderaiser/cloudcmd/runs/4521000330?check_suite_focus=true#step:11:278

**Comment by timoknapp** [comment]
> @timoknapp could you please help, docker containers not created because of en error https://github.com/coderaiser/cloudcmd/runs/4521000330?check_suite_focus=true#step:11:278

Hi @coderaiser ,

I could not make it to start with the investigation yet. Its still on my bucket list though.  🙏

**Comment by mchromy** [comment]
Hey. Same problem at raspberry 4, adding stack in portainer
`version: '2'
services:
  web:
    ports:
      - 7000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    image: coderaiser/cloudcmd`
Added ok, but cloudcmd stopped with error
`Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion (0) == (uv_gettimeofday(&tv))' failed.`

**Comment by timoknapp** [comment]
Hey @coderaiser, is the issue resolved now? I just had a look into the Pipeline and it seems that the build job "Build and push alpine-image" runs correctly now.
https://github.com/coderaiser/cloudcmd/runs/4616749170?check_suite_focus=true

Maybe this also resolves the issues for the rest of you. Can you please have a look again: @yllekz @mchromy ?

**Comment by yllekz** [comment]
Not sure if I have to wait for Docker Hub to update, but when I went to pull a new image it did not retrieve a new one, it still indicated the image from 2021-12-23 was the newest. I'll try again in a few hours.

**Comment by timoknapp** [comment]
> Not sure if I have to wait for Docker Hub to update, but when I went to pull a new image it did not retrieve a new one, it still indicated the image from 2021-12-23 was the newest. I'll try again in a few hours.

Hmm no it seems that the latest release is actually from 2021-12-23

<img width="967" alt="image" src="https://user-images.githubusercontent.com/11437666/148105901-562ee173-e9f0-4544-b05d-bb3def889b8f.png">


But this then means, that the issue @coderaiser noticed does not relate to your initial problem.

**Comment by coderaiser** [comment]
@timoknapp yes the issue with building images is resolved, there was problem with new name of `python` package in `alpine`.

About `raspberry` can you reproduce this issue with latest image?

**Comment by timoknapp** [comment]
> 

@coderaiser yes I could reproduce the issue and I also found a way of resolving it. It seems to be related to the Node base image. I updated the base images and created a new PR for it (#362)

**Comment by coderaiser** [comment]
@timoknapp thanks a lot for a fix :) 🎉 ! 
I just [restarted actions](https://github.com/coderaiser/cloudcmd/actions/runs/1658706848), could you please try `v15.9.13` when it published, @yllekz is it works for you?

**Comment by timoknapp** [comment]
@yllekz Could you perform a retest yet?  I personally did it and it works again. So please get back to us such that the issue can be resolved :)

**Comment by yllekz** [comment]
Docker Hub still won't pull the latest image, it's still saying the one from late December is the latest?

**Comment by timoknapp** [comment]
> ~~Docker Hub still won't pull the latest image, it's still saying the one from late December is the latest?~~
> 
> 
> 
> Update: It's working now! Took a while for Docker Hub to react but it finally pulled the new image and now it's all set.

@yllekz great! Thanks for the feedback. Lets close this issue @coderaiser :)

**Comment by coderaiser** [comment]
That's amazing! @timoknapp thanks a lot for you help 🎉 !
